import Head from 'next/head'
import { AppShell, Navbar, Footer, Header } from '@mantine/core';
import PipelinesTable from '@/components/pipelines_table'
import { Title } from '@mantine/core';


export default function Home() {
  return (
    <>
      <Head>
        <title>DataFloz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
          padding="md"
          header={<Header height={60} p="xs">DataFloz</Header>}
          footer={
            <Footer height={60} p="md">
              Application footer
            </Footer>
          }
          styles={(theme) => ({
            main: { backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0] },
        })}
      >
      <Title>Pipelines-some name</Title>
      <PipelinesTable 
          pipelines={[
            {name: 'first', inputTopic: 'input1', outputTopic: 'out1'},
            {name: 'second', inputTopic: 'out1', outputTopic: 'out2'},
            {name: 'third', inputTopic: 'input1', outputTopic: 'out3'},
          ]}
        ></PipelinesTable>
    </AppShell>
    </>
  )
}
