name: 'sample-config'
running_infrastructure:
  infrustructure_type: container
connectors:
  -
    name: 'local-kafka-connector'
    type: 'kafka'
    brokers: 'kafka:29092'
    group_id: 'some-group-id'
pipelines:
  -
    name: 'calculate-fullname'
    input:
      type: 'kafka'
      topic: 'persons'
    output:
      type: 'kafka'
      topic: 'persons-with-full-name'
    transformation:
      type: 'sql'
      sql_query: 'SELECT *, first_name || " " || last_name as full_name FROM msg'
  -
    name: 'calculate-is-adult'
    input:
      type: 'kafka'
      topic: 'persons-with-full-name'
    output:
      type: 'kafka'
      topic: 'persons-with-full-name-is-adult'
    transformation:
      type: 'sql'
      sql_query: 'SELECT *, age > 18 as is_adult FROM msg'
  -
    name: 'filter-only-abults'
    input:
      type: 'kafka'
      topic: 'persons-with-full-name-is-adult'
    output:
      type: 'kafka'
      topic: 'persons-only-adults'
    transformation:
      type: 'sql'
      sql_query: 'SELECT * FROM msg WHERE is_adult'
  -
    name: 'calculate-with-ML'
    input:
      type: 'kafka'
      topic: 'persons-with-full-name'
    output:
      type: 'kafka'
      topic: 'persons-with-ml'
    transformation:
      type: 'pickle'
      file_name: 'test.pkl'
    