name: 'sample-config'
connectors:
  -
    name: 'local-kafka-connector'
    type: 'kafka'
    brokers: 'kafka:29092'
    group_id: 'some-group-id'
pipelines:
  -
    name: 'sample-first-pipeline'
    input:
      type: 'kafka'
      topic: 'some-in-topic'
    output:
      type: 'kafka'
      topic: 'some-out-topic'
    transformation:
      type: 'container'
      container-image: 'some-image-name'
  -
    name: 'sample-second-pipeline'
    input:
      type: 'kafka'
      topic: 'some-out-topic'
    output:
      type: 'kafka'
      topic: 'some-second-out-topic'
    transformation:
      type: 'sql'
      sql_query: 'SELECT * FROM msg WHERE age > 18'
  -
    name: 'sample-third-pipeline'
    input:
      type: 'kafka'
      topic: 'some-out-topic'
    output:
      type: 'kafka'
      topic: 'some-third-out-topic'
    transformation:
      type: 'http'
      http_url: 'some-http-url'
      headers: 
        key1: 'value1'
        key2: 'value2'
      params:
        key1: 'value1'
        key2: 'value2'