name: 'sample-config'
running_infrastructure:
  infrustructure_type: container
connector:
    name: 'local-kafka-connector'
    type: 'kafka'
    brokers: 'kafka:29092'
    group_id: 'some-group-id'
pipelines:
  -
    name: 'calculate-fullname'
    input:
      type: 'kafka'
      topic: 'persons'
    output:
      type: 'kafka'
      topic: 'persons-with-full-name'
    transformation:
      type: 'sql'
      sql_query: 'SELECT *, first_name || " " || last_name as full_name FROM msg'
  -
    name: 'calculate-is-adult'
    input:
      type: 'kafka'
      topic: 'persons-with-full-name'
    output:
      type: 'kafka'
      topic: 'persons-with-full-name-is-adult'
    transformation:
      type: 'sql'
      sql_query: 'SELECT *, age > 18 as is_adult FROM msg'
  -
    name: 'filter-only-abults'
    input:
      type: 'kafka'
      topic: 'persons-with-full-name-is-adult'
    output:
      type: 'kafka'
      topic: 'persons-only-adults'
    transformation:
      type: 'sql'
      sql_query: 'SELECT * FROM msg WHERE is_adult'
  -
    name: 'calculate-with-ML'
    input:
      type: 'kafka'
      topic: 'persons-with-full-name'
    output:
      type: 'kafka'
      topic: 'persons-with-ml'
    transformation:
      type: 'pickle'
      file_name: 'test.pkl'  
  -
    name: 'calculate-with-HTTP'
    input:
      type: 'kafka'
      topic: 'persons-with-full-name'
    output:
      type: 'kafka'
      topic: 'persons-with-http'
    transformation:
      type: 'http'
      http_url: 'http://test-url/test'
      headers:
        - "authorization": "secret"
        - "header-2": "some-header"
      params:
        - "param1": "value1"
  -
    name: 'calculate-with-container'
    input:
      type: 'kafka'
      topic: 'persons-with-full-name'
    output:
      type: 'kafka'
      topic: 'persons-with-container'
    transformation:
      type: 'container'
      container-image: 'test-image-name:latest'
    