name: 'sample-config'
connectors:
  -
    name: 'local-kafka-connector'
    type: 'kafka'
    brokers: 'kafka:29092'
    group_id: 'some-group-id'
pipelines:
  -
    name: 'sample-first-pipeline'
    input:
      type: 'kafka'
      topic: 'some-in-topic'
    output:
      type: 'kafka'
      topic: 'some-out-topic'
    transformation:
      type: 'sql'
      sql_query: 'SELECT * FROM msg WHERE name = "ofir"'
  -
    name: 'sample-second-pipeline'
    input:
      type: 'kafka'
      topic: 'some-out-topic'
    output:
      type: 'kafka'
      topic: 'some-second-out-topic'
    transformation:
      type: 'sql'
      sql_query: 'SELECT * FROM msg WHERE age > 18'