on: pull_request
name: client-quality-gate
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Node.js dependencies
        run: cd ./client && npm ci
      - name: Lint
        run: cd ./client && npm run lint
      - name: Build
        run: cd ./client && npm run build
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: cd ./client && npm run build
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: cd ./client && npm run lint
  prettier:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Prettier check
        run: cd ./client && npx prettier -c .