on: pull_request

jobs:
  runner-lint:
    runs-on: ubuntu-latest
    name: Executes pylint runner
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r ./runner/requirements.txt
          echo "PYTHON_PATH=./runner" >> $GITHUB_ENV
      - name: Analysing the code with pylint
        run: pylint ./runner
  pipeline-lint:
    runs-on: ubuntu-latest
    name: Executes pylint pipeline
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r ./pipeline/requirements.txt
          echo "PYTHON_PATH=./pipeline" >> $GITHUB_ENV
      - name: Analysing the code with pylint
        run: pylint ./pipeline