on: pull_request
name: quality-gates
jobs:
  client:
    runs-on: ubuntu-latest
    name: client-quality-gate
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Node.js dependencies
        run: cd ./client && npm ci
      - name: Build
        run: cd ./client && npm run build
      - name: Lint
        run: cd ./client && npm run lint
      - name: Prettier check
        run: cd ./client && npm run prettier:check
  runner:
    runs-on: ubuntu-latest
    name: runner-quality-gate
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r ./runner/requirements.txt
          echo "PYTHON_PATH=./runner" >> $GITHUB_ENV
      - name: Analysing the code with pylint
        run: pylint ./runner
  pipeline:
    runs-on: ubuntu-latest
    name: pipeline-quality-gate
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r ./pipeline/requirements.txt
          echo "PYTHON_PATH=./pipeline" >> $GITHUB_ENV
      - name: Analysing the code with pylint
        run: pylint ./pipeline
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with your requirements file if needed
      - name: Run unit tests
        run: python -m unittest discover